#!/usr/bin/env python3
"""Generate a single-file JSON Schema compound document for offline adopters.

The bundle is a **distribution artifact**, not another Weaver contract. It lives
outside ``contracts/json/`` so contract inventory tooling cannot accidentally
classify it as Core. Every embedded schema preserves its original absolute
``$id``; compliant Draft 2020-12 implementations can discover those embedded
resources from the compound document and resolve the existing cross-schema
references without network access.

The content-addressed ``well-known/contracts.json`` index is the source of truth.
The generator verifies each source schema against the index before embedding it.
It is intentionally stdlib-only.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from collections.abc import Iterable
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
INDEX_PATH = REPO_ROOT / "well-known" / "contracts.json"
OUTPUT_PATH = REPO_ROOT / "contracts" / "bundles" / "weaver-contracts.bundle.json"
DRAFT_2020_12 = "https://json-schema.org/draft/2020-12/schema"


def _normalized_bytes(raw: bytes) -> bytes:
    return raw.replace(b"\r\n", b"\n")


def _sha256(raw: bytes) -> str:
    return hashlib.sha256(raw).hexdigest()


def _load_index() -> dict[str, Any]:
    value = json.loads(INDEX_PATH.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise RuntimeError("well-known/contracts.json must contain a JSON object")
    return value


def _entries(index: dict[str, Any]) -> Iterable[tuple[str, dict[str, Any]]]:
    for tier in ("core", "extended"):
        values = index.get(tier)
        if not isinstance(values, list):
            raise RuntimeError(f"contracts index field {tier!r} must be a list")
        for entry in values:
            if not isinstance(entry, dict):
                raise RuntimeError(f"contracts index {tier!r} entry must be an object")
            yield tier, entry


def _load_verified_schema(entry: dict[str, Any]) -> dict[str, Any]:
    required = ("name", "$id", "path", "sha256")
    missing = [
        key
        for key in required
        if not isinstance(entry.get(key), str) or not entry[key]
    ]
    if missing:
        fields = ", ".join(missing)
        raise RuntimeError(
            f"contract entry missing non-empty string field(s): {fields}"
        )

    source = (REPO_ROOT / entry["path"]).resolve()
    try:
        source.relative_to(REPO_ROOT)
    except ValueError as exc:
        raise RuntimeError(
            f"contract source escapes repository: {entry['path']}"
        ) from exc
    if not source.is_file():
        raise RuntimeError(f"contract source does not exist: {entry['path']}")

    normalized = _normalized_bytes(source.read_bytes())
    actual_hash = _sha256(normalized)
    expected_hash = entry["sha256"].lower()
    if actual_hash != expected_hash:
        raise RuntimeError(
            f"contract hash mismatch for {entry['path']}: "
            f"index={expected_hash} source={actual_hash}"
        )

    schema = json.loads(normalized)
    if not isinstance(schema, dict):
        raise RuntimeError(f"schema must contain a JSON object: {entry['path']}")
    if schema.get("$id") != entry["$id"]:
        raise RuntimeError(
            f"schema $id mismatch for {entry['path']}: "
            f"index={entry['$id']!r} source={schema.get('$id')!r}"
        )
    return schema


def build_bundle() -> dict[str, Any]:
    index = _load_index()
    definitions: dict[str, Any] = {}

    for tier, entry in _entries(index):
        schema = _load_verified_schema(entry)
        key = f"{tier}__{entry['name']}"
        if key in definitions:
            raise RuntimeError(f"duplicate bundle definition key: {key}")
        definitions[key] = schema

    return {
        "$schema": DRAFT_2020_12,
        "$comment": (
            "Generated distribution artifact. Embedded resources preserve "
            "their canonical $id values; do not edit this file by hand."
        ),
        "x_weaver_contract_version": index.get("contract_version"),
        "$defs": definitions,
    }


def render_bundle(bundle: dict[str, Any]) -> str:
    return json.dumps(bundle, indent=2, sort_keys=False) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if the committed bundle is missing or stale.",
    )
    args = parser.parse_args()

    try:
        expected = render_bundle(build_bundle())
    except (OSError, ValueError, RuntimeError, json.JSONDecodeError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    if args.check:
        if not OUTPUT_PATH.is_file():
            print(
                f"ERROR: {OUTPUT_PATH.relative_to(REPO_ROOT)} is missing. "
                "Run `python scripts/generate_schema_bundle.py`.",
                file=sys.stderr,
            )
            return 1
        actual = OUTPUT_PATH.read_text(encoding="utf-8")
        if actual != expected:
            print(
                f"ERROR: {OUTPUT_PATH.relative_to(REPO_ROOT)} is stale. "
                "Run `python scripts/generate_schema_bundle.py` and commit the result.",
                file=sys.stderr,
            )
            return 1
        print(f"OK: {OUTPUT_PATH.relative_to(REPO_ROOT)} is up to date.")
        return 0

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(expected, encoding="utf-8", newline="\n")
    print(f"Wrote {OUTPUT_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
